// <auto-generated />
using GovDelivery.ConsoleApp;
using GovDelivery.Entity.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GovDelivery.ConsoleApp.Migrations
{
    [DbContext(typeof(GovDeliveryContext))]
    partial class GovDeliveryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GovDelivery.Entity.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AllowUserInitiatedSubscriptions");

                    b.Property<string>("Code");

                    b.Property<bool>("DefaultOpen");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid?>("ParentCategoryId");

                    b.Property<string>("QuickSubscribePageCode");

                    b.Property<string>("ShortName")
                        .IsRequired();

                    b.Property<Guid?>("TopicId");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GovDelivery.Entity.Models.CategorySubscription", b =>
                {
                    b.Property<Guid>("SubscriberId");

                    b.Property<Guid>("CategoryId");

                    b.HasKey("SubscriberId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategorySubscriptions");
                });

            modelBuilder.Entity("GovDelivery.Entity.Models.CategoryTopic", b =>
                {
                    b.Property<Guid>("TopicId");

                    b.Property<Guid>("CategoryId");

                    b.HasKey("TopicId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryTopics");
                });

            modelBuilder.Entity("GovDelivery.Entity.Models.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("TopicId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("GovDelivery.Entity.Models.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BulletinFrequency");

                    b.Property<string>("CountryCode");

                    b.Property<string>("Email");

                    b.Property<int>("GovDeliveryId");

                    b.Property<string>("Link");

                    b.Property<string>("Phone");

                    b.Property<bool>("SendSubscriberUpdateNotifications");

                    b.HasKey("Id");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("GovDelivery.Entity.Models.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<int>("DefaultPagewatchResults");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<bool>("PagewatchAutosend");

                    b.Property<bool>("PagewatchEnabled");

                    b.Property<bool>("PagewatchSuspended");

                    b.Property<int?>("PagewatchType");

                    b.Property<string>("RssFeedDescription");

                    b.Property<string>("RssFeedTitle");

                    b.Property<string>("RssFeedUrl");

                    b.Property<bool>("SendByEmailEnabled");

                    b.Property<string>("ShortName");

                    b.Property<bool>("WatchTaggedContent");

                    b.Property<bool>("WirelessEnabled");

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("GovDelivery.Entity.Models.TopicSubscription", b =>
                {
                    b.Property<Guid>("SubscriberId");

                    b.Property<Guid>("TopicId");

                    b.HasKey("SubscriberId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("TopicSubscriptions");
                });

            modelBuilder.Entity("GovDelivery.Entity.Models.Category", b =>
                {
                    b.HasOne("GovDelivery.Entity.Models.Category", "ParentCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentCategoryId");

                    b.HasOne("GovDelivery.Entity.Models.Topic")
                        .WithMany("Categories")
                        .HasForeignKey("TopicId");
                });

            modelBuilder.Entity("GovDelivery.Entity.Models.CategorySubscription", b =>
                {
                    b.HasOne("GovDelivery.Entity.Models.Category", "Category")
                        .WithMany("EmailSubscriberCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GovDelivery.Entity.Models.Subscriber", "Subscriber")
                        .WithMany("CategorySubscriptions")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GovDelivery.Entity.Models.CategoryTopic", b =>
                {
                    b.HasOne("GovDelivery.Entity.Models.Category", "Category")
                        .WithMany("Topics")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GovDelivery.Entity.Models.Topic", "Topic")
                        .WithMany("TopicCategories")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GovDelivery.Entity.Models.Page", b =>
                {
                    b.HasOne("GovDelivery.Entity.Models.Topic")
                        .WithMany("Pages")
                        .HasForeignKey("TopicId");
                });

            modelBuilder.Entity("GovDelivery.Entity.Models.TopicSubscription", b =>
                {
                    b.HasOne("GovDelivery.Entity.Models.Subscriber", "Subscriber")
                        .WithMany("TopicSubscriptions")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GovDelivery.Entity.Models.Topic", "Topic")
                        .WithMany("EmailSubscriberTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
